// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpSAluUChJyvG5vcJGZPvkC7bi5YWfR-I',
    appId: '1:652892184045:android:9b6a5fc85efba7c2501be4',
    messagingSenderId: '652892184045',
    projectId: 'hyper-garage-sale-zach',
    storageBucket: 'hyper-garage-sale-zach.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCQaowAbRnl48FyJehhtqpPbqiNLm8mjQ',
    appId: '1:652892184045:ios:4401b88e54e319f5501be4',
    messagingSenderId: '652892184045',
    projectId: 'hyper-garage-sale-zach',
    storageBucket: 'hyper-garage-sale-zach.appspot.com',
    androidClientId: '652892184045-hpnekl4o42blrj5uecenueann97b14fm.apps.googleusercontent.com',
    iosClientId: '652892184045-934jes6frsqbgl7he8bbs24uk6igs2sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.hyperGarageSale',
  );
}
